### ISSUE TITLE
Incorrect rem value

### ISSUE THREAD

**Issue by leoamros** [acwtools/accss#4]
I use a lot of rem values in my css and after converting a css file i got incorrect values.

Input
`top: 1.313rem;
left: 0.3125rem;
right: 0.3125rem;
height: 0.375rem;`

Output:
`top:1.313rem;left:.1225rem;right:.1225rem;height:3755rem;`

Can you help me to find the problem?

I figured out, when you have 0.xxx rem value it cant convert it correctly, but when you have .xxx rem it's working fine.

**Comment by gandalfSievers** [comment]
Hi,

thank you for your input. Unfortunately, i can‘t reproduce your problem based on the information you provided.

After cloning master on Mac Os, running ./configure && make, i completed the partial rule you provided and piped it into accss:

`echo "a {top: 1.313rem; left: 0.3125rem; right: 0.3125rem; height: 0.375rem;}" | src/accss `

The result is as expected:
`a{top:1.313rem;left:.3125rem;right:.3125rem;height:.375rem}`

Which operating system do you use? Did you compile in 32bit or 64bit? Did you use any options for accss?

Can you provide a complete example?

I'm looking forward to solve your issue!

Best regards
Gandalf

**Comment by leoamros** [comment]
I use `Ubuntu 16.04.1 LTS` 64bit and I tried with the code you wrote on Server and Kubuntu too. Same result

Input (Kubuntu):
`echo "a {top: 1.313rem; left: 0.3125rem; right: 0.3125rem; height: 0.375rem;}" | accss`

Output:
`a{top:1.313rem;left:.1225rem;right:.1225rem;height:3755rem}`

So without any parameters it gives this result. I checked the whole css and every 0.*** value is converted in the wrong way.

Here is an example for animate.css:

[animate.css original](http://asztaloscenter.sttc.hu/test/animate.css) 
[animate.css minified](http://asztaloscenter.sttc.hu/test/animate.conv.css)

At `@-webkit-keyframes bounce` you can see the problem:

Input (Server):
`-webkit-animation-timing-function: cubic-bezier(0.215, 0.610, 0.355, 1.000);`
`animation-timing-function: cubic-bezier(0.215, 0.610, 0.355, 1.000);`

Output:
`-webkit-animation-timing-function:cubic-bezier(2155,6100,3555,1);animation-timing-function:cubic-bezier(2155,6100,3555,1);`

If you delete all 0's from the css it works fine, but in a bigger project with lot of css code it's a long work :)

[animate.css without 0's](http://asztaloscenter.sttc.hu/test/animate.dev.css)
[animate.css minified correctly](http://asztaloscenter.sttc.hu/test/animate.conv.dev.css)

I hope this helps to find the problem.

**Comment by gandalfSievers** [comment]
Hi,

sorry for the delay, I was busy with holiday preparations. I was able to reproduce your issue and I hopefully fixed it in #5, which I merged to master.

Can you confirm that? Feel free to reopen the issue.

Merry Christmas
